controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_home:
    path: /
    controller: App\Controller\HomeController::index
    
app_actualities:
    path: /actualites
    controller: App\Controller\ActualitiesController::index

app_trainings:
    path: /formations
    controller: App\Controller\TrainingsController::index
